# Production environment override
services:
  php:
    image: ${REGISTRY_IMAGE_PHP:-ghcr.io/leenup/leenup-backend-php}
    build:
      context: ./api
      target: frankenphp_prod
    ports: []
    expose:
      - "80"
    networks:
      - web
      - default
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=${POSTGRES_CHARSET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  pwa:
    image: ${REGISTRY_IMAGE_PWA:-ghcr.io/leenup/leenup-backend-pwa}
    build:
      context: ./pwa
      dockerfile: Dockerfile
      target: prod
    expose:
      - "3000"
    networks:
      - web
      - default

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

networks:
  web:
    external: true
