sonar.projectKey=leenup_leenup-backend
sonar.organization=leenup

# Nom et version du projet
sonar.projectName=leenup-backend
sonar.projectVersion=1.0

# Chemins source (dans le dossier api/)
sonar.sources=api/src
sonar.tests=api/tests

# Exclusions
sonar.exclusions=**/vendor/**,**/var/**,**/public/**,**/migrations/**,**/*.js,**/node_modules/**

# Langage principal
sonar.language=php
sonar.php.coverage.reportPaths=api/coverage.xml
