security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        # 🔐 Firewall dédié au login JSON (/auth)
        login:
            pattern: ^/auth
            stateless: true
            provider: users
            json_login:
                check_path: /auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # 🔐 Firewall principal JWT + refresh
        main:
            pattern: ^/
            stateless: true
            provider: users
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        - { path: ^/contexts, roles: PUBLIC_ACCESS }
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Hachage volontairement faible en test : bcrypt coût 13 = ~0,4 s par hash.
            # https://symfony.com/doc/current/security/passwords.html#configuring-a-password-hasher
            App\Entity\User:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
