<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add mentor availability tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mentor_availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mentor_id INT NOT NULL, day_of_week SMALLINT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B5C1F757F5D05C ON mentor_availability (mentor_id)');
        $this->addSql('ALTER TABLE mentor_availability ADD CONSTRAINT FK_5B5C1F757F5D05C FOREIGN KEY (mentor_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE mentor_availability_exception (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mentor_id INT NOT NULL, date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1A1E9D7D7F5D05C ON mentor_availability_exception (mentor_id)');
        $this->addSql('ALTER TABLE mentor_availability_exception ADD CONSTRAINT FK_1A1E9D7D7F5D05C FOREIGN KEY (mentor_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mentor_availability DROP CONSTRAINT FK_5B5C1F757F5D05C');
        $this->addSql('ALTER TABLE mentor_availability_exception DROP CONSTRAINT FK_1A1E9D7D7F5D05C');
        $this->addSql('DROP TABLE mentor_availability');
        $this->addSql('DROP TABLE mentor_availability_exception');
    }
}
