<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260107142224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, family VARCHAR(100) NOT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, category VARCHAR(50) NOT NULL, level INT NOT NULL, image_url VARCHAR(255) NOT NULL, conditions JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_161498D377153098 ON card (code)');
        $this->addSql('CREATE TABLE user_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, obtained_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source VARCHAR(50) DEFAULT NULL, meta JSON DEFAULT NULL, user_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_user_card_user ON user_card (user_id)');
        $this->addSql('CREATE INDEX idx_user_card_card ON user_card (card_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_card_user_card ON user_card (user_id, card_id)');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41A4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41AA76ED395');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41A4ACC9A20');
        $this->addSql('DROP TABLE card');
        $this->addSql('DROP TABLE user_card');
    }
}
