<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261002155203 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add token_transaction (token history) and backfill an initial_balance row for existing users';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE token_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, type VARCHAR(30) NOT NULL, balance_after INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, session_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E06574BA76ED395 ON token_transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_5E06574B613FECDF ON token_transaction (session_id)');
        $this->addSql('CREATE INDEX idx_token_transaction_user_created ON token_transaction (user_id, created_at)');
        $this->addSql('ALTER TABLE token_transaction ADD CONSTRAINT FK_5E06574BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE token_transaction ADD CONSTRAINT FK_5E06574B613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE SET NULL NOT DEFERRABLE');

        // L'historique passé n'est pas reconstituable : on part du solde actuel de chaque utilisateur.
        $this->addSql(<<<'SQL'
            INSERT INTO token_transaction (amount, type, balance_after, created_at, user_id)
            SELECT token_balance, 'initial_balance', token_balance, NOW(), id
            FROM "user"
            WHERE token_balance > 0
            SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE token_transaction DROP CONSTRAINT FK_5E06574BA76ED395');
        $this->addSql('ALTER TABLE token_transaction DROP CONSTRAINT FK_5E06574B613FECDF');
        $this->addSql('DROP TABLE token_transaction');
    }
}
